### ISSUE TITLE
[travis] Build error because of Elixir script

### ISSUE THREAD

**Issue by rafaelcn** [DestructHub/ProjectEuler#114]
The Elixir `solution_1` in `Problem001` seems to be wrong and the scripts return with a build error, hence the build error status. The error can be seen below and maybe @lubien could give us a hint in how to solve it:
 
```
Builded Problem001/Elixir/solution_1.exs: Answer: =INFO REPORT==== 1-Sep-2017::20:14:24 ===
    application: logger
    exited: {{shutdown,
                 {failed_to_start_child,'Elixir.GenEvent',
                     {undef,
                         [{gen,debug_options,[[]],[]},
                          {'Elixir.GenEvent',init_it,6,
                              [{file,"lib/gen_event.ex"},{line,535}]},
                          {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,247}]}]}}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
233168: 0.47s
@Building next Problem002/Elixir/solution_1.ex:  ** (UndefinedFunctionError) undefined function: Enum.reduce_while/3
    (elixir) Enum.reduce_while(#Stream<[enum: #Function<43.95910526/2 in Stream.unfold/2>, funs: [#Function<31.95910526/1 in Stream.filter/2>]]>, 0, #Function<2.106859709 in file:solution_1.ex>)
    (elixir) lib/code.ex:307: Code.require_file/2
```

**Comment by ryukinix** [comment]
Weird. Where this error happens? Travis server or in your build machine?

**Comment by ryukinix** [comment]
This is indeed a job for @lubien or @kress95

**Comment by ryukinix** [comment]
Elixir monkeys

**Comment by rafaelcn** [comment]
Assigned them to the task! :-)

**Comment by ryukinix** [comment]
I doubt anyone of them will fix that shit (too busy, one of them with working and the other with [audiovisual entertainment](https://myanimelist.net/anime/185/Initial_D_First_Stage))

**Comment by lubien** [comment]
Did you try restart the build?

**Comment by rafaelcn** [comment]
Just restarted. Lets see where it will stop.

**Comment by lubien** [comment]
I god I forgot how the build was slow. Cache when?

**Comment by rafaelcn** [comment]
I think there's no way to cache the tools needed for the project. Each build is ran in a new boxed environment each time.

**Comment by lubien** [comment]
What about making a Docker image?

**Comment by rafaelcn** [comment]
I didn't think of that, is it possible to make a docker image to run in Travis?

**Comment by lubien** [comment]
Also, Travis CI does have cache. I've used mostly to cache dependencies

**Comment by lubien** [comment]
@rafaelcn totally. I've done it before

**Comment by rafaelcn** [comment]
There you go! You could make some changes in the `travis.yml` then 👍

**Comment by lubien** [comment]
As soon as possible

**Comment by ryukinix** [comment]
Caching dependencies will fix the desired behavior to use docker on issue #55

**Comment by lubien** [comment]
Seems like the build went just fine @rafaelcn 

Maybe some BEAM issue? The nine nines (99.9999999% reliability) gives us that 0.0000001% of failing too. Jk

**Comment by rafaelcn** [comment]
That should be it @lubien. Just verified it. Lets close it move on to the #55.
