### ISSUE TITLE
Blame Board: the worst solutions

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#12]
I'll add the `--blame` option to stats.py print the solutions tagged as `_slow_`. Would be great  if we had the time of each one, but some solutions is reaaally bad, take almost hours to finish. After implemented that, I print the path of the solutions here.

**Comment by ryukinix** [comment]
We can:

Print the path of blame solutions
```
[lerax@starfox ProjectEuler (master)]$ python stats.py --list --path --blame
Command: Blame Path List
Problem005/Python/solution_slow_1.py
Problem034/Python/solution_slow_1.py
Problem050/Python/solution_slow_1.py
Problem072/Python/solution_slow_1.py
Problem092/Python/solution_slow_1.py
Problem092/Python/solution_slow_2.py
Problem145/Python/solution_slow_1.py
Problem357/Python/solution_slow_1.py
Problem439/Python/solution_slow_1.py
Problem473/Python/solution_slow_1.py
Problem473/Python/solution_slow_2.py
Problem501/Python/solution_slow_1.py
Problem005/Elixir/solution_slow_1.exs
Problem027/CommonLisp/solution_slow_1.lisp
Problem010/Haskell/solution_slow_1.hs
Problem014/Haskell/solution_slow_1.hs
Problem031/Haskell/solution_slow_1.hs
```

Print the languages whose have blame solutions
```
[lerax@starfox ProjectEuler (master)]$ python stats.py --list --blame
Command: Blame All List
CommonLisp
Elixir
Haskell
Python
```
Print the count of blame solutions per language
```
[lerax@starfox ProjectEuler (master)]$ python stats.py --list --count --blame
Command: Count List Blame
            Solutions
Solutions          17
Python             12
Haskell             3
Elixir              1
CommonLisp          1
```

You can try yet build, I add support for that, but is really slow. Because all are blame solutions.

Try:

* `python stats.py --build --all --blame`
* `python stats.py --build --search blame_language --blame`

Ps.: "Blame Solution" is a concept, doesn't need makes sense at english. The blame solutions fuck the build, because are guilty.

**Comment by ryukinix** [comment]
@rafaelcn, your button.

**Comment by rafaelcn** [comment]
Oh yea indeed!
