### ISSUE TITLE
[travis] C building: weird behavior at travis server, -lm not found

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#13]
```
$ python stats.py --all --build

Command: All Build
Builded Problem001/C/solution_1.c: Answer: 233168: 0.00s
Builded Problem002/C/solution_1.c: Answer: 4613732: 0.00s
@Building next Problem027/C/solution_1.c:  /tmp/cch6tzam.o: In function `is_prime':

/home/travis/build/DestructHub/ProjectEuler/Problem027/C/solution_1.c:36: undefined reference to `sqrt'

collect2: ld returned 1 exit status
```

**Comment by rafaelcn** [comment]
Tha's on the server, the `-lm` links the code with the math library.

**Comment by ryukinix** [comment]
Look here: [stats.py](https://github.com/DestructHub/ProjectEuler/blob/master/stats.py#L134)

**Comment by rafaelcn** [comment]
Too superficial don't you think? I should add `-Wall -Werr -std=c++0x` as well. Anyway, is this bug fixed?

**Comment by ryukinix** [comment]
No. In the server don't work, in local machine works. I need install this shit on server too?

**Comment by ryukinix** [comment]
I don't want useless warnings messages on building because `C++` is oriented with this. That type of thing will release garbage on my beautiful log even in good solutions in CPlusPlus. And this is not the problem, after all.

By other hand, in cases of errors, `-Werr` can be useful?

**Comment by ryukinix** [comment]
![c](https://cloud.githubusercontent.com/assets/7642878/18152688/204e8e5a-6fce-11e6-8512-8d56ab7f994f.jpg)

**Comment by rafaelcn** [comment]
No, C++ warnings are super useful, and it isn't oriented to warnings, your argument does count to any language actually, putting it aside, I agree with you that this would pollute the logs and should be verified with the Makefile instead. And no, `-Werr` will just transform any warning into an error, which in some cases it might not be a good thing. 

Concerning about the math library I think it should be installed on the server as well, but I wonder why it isn't installed already... :thought_balloon:

**Comment by ryukinix** [comment]
I don't care. I just wanna fix that problem to enable building C++ again, whose is disabled.

**Comment by rafaelcn** [comment]
Oh boy, your Makefile is wrong, it actually doesn't work over here with this instruction:

```
CXX = gcc
LFLAGS = -lm -Wall -o
TARGET =  solution_1
EXTENSION_TARGET = c
EXTENSION_OUT = out


all: 
        $(CXX) $(LFLAGS) $(TARGET).$(EXTENSION_OUT) $(TARGET).$(EXTENSION_TARGET)
```

That would be translated to:

`gcc -lm -Wall -o solution_1.c solution_1.out`

This is wrong, to link libraries you have to put the `-l` flag on the end of the instruction. The commit fix was sent.

**Comment by ryukinix** [comment]
@rafaelcn On my machine works, BTW. I think the problem is your existance.

**Comment by rafaelcn** [comment]
It probably works because it isn't linking to `libm.so`. Dunno though, here it doesn't work, and also on the travis server, the problem is probably there.

**Comment by rafaelcn** [comment]
Anyway, blame one another is not going to work

**Comment by ryukinix** [comment]
What happens in your machine?

**Comment by rafaelcn** [comment]
```ranu@ranu-laptop ~/Github/DestructHub/ProjectEuler/Problem048/C (makefile-fix) $ gcc -lm -Wall solution_1.c
/tmp/cczRZ3c1.o: In function `main':
solution_1.c:(.text+0xa3): undefined reference to `pow'
solution_1.c:(.text+0xbc): undefined reference to `fmod'
collect2: error: ld returned 1 exit status
```

**Comment by ryukinix** [comment]
NICE!

**Comment by rafaelcn** [comment]
It seems that this behavior only appears with gcc, g++ does the job of linking right wherever you place the `-l` flag, but this (Problem048) code isn't valid c++ code.

**Comment by ryukinix** [comment]
@rafaelcn The code has problems. You wanna put more problems like recodifieing the C solution to a bad language as C++. I don't understand, really on my machine works. I think the problems is other thing. Maybe a gcc-multlib or other shit like that,

**Comment by rafaelcn** [comment]
No, I don't, I just said it isn't a valid C++ code. Regarding the problem, we will see if this solves the problem.

**Comment by ryukinix** [comment]
Great.
![kixqm2](https://cloud.githubusercontent.com/assets/7642878/18167720/7d86ba48-7028-11e6-8b19-64540913653c.jpg)

**Comment by ryukinix** [comment]
![kixqm2](https://cloud.githubusercontent.com/assets/7642878/18167783/e0a9d7c2-7028-11e6-843a-abcbacd56056.jpg)

Yes, in my machine works.

**Comment by rafaelcn** [comment]
This only affects C. Changing the title of the issue.

**Comment by ryukinix** [comment]
@rafaelcn Ok
