### ISSUE TITLE
Sending result of build system output of travis to currently PR as comment

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#138]
This should simplify a lot of things to analysis PRs of new comers about efficiency and correctness, as described briefly on the end of this PR #137

**Comment by ryukinix** [comment]
Closing this for lacking of activity. This will not be implemented.

**Comment by A-Hilaly** [comment]
Sorry i didn't work on this as we discussed months ago. This still an amazing feature to implement!
I will work on it, once i finish my exams (first July probably :-) )

**Comment by A-Hilaly** [comment]
Still an interesting feature to implement. I'll reopen this issue once ready to work on it !
