### ISSUE TITLE
Differential build PR bugs

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#140]
Need to fix:

- [ ] `python3 stats.py --build --files test` build all solutions and shouldn't.
- [ ] `push` travis events fails on build as [this](https://travis-ci.org/DestructHub/ProjectEuler/builds/301674042?utm_source=github_status&utm_medium=notification)

Related to #137  #139  #136

**Comment by A-Hilaly** [comment]
I I said in #139 `python3 stats.py --build --files test` is just an undiscussed case in stats.py. I believed that changing one of the core files would require a build for all the problems. Anyways ill open a PR changing/controlling this

**Comment by A-Hilaly** [comment]
for `push` travis events fails, we need to add more verbose on the ./test to see whats happening

**Comment by ryukinix** [comment]
> as I said in #139 python3 stats.py --build --files test is just an undiscussed case in stats.py. I believed that changing one of the core files would require a build for all the problems. Anyways ill open a PR changing/controlling this

Hmm, I forgot about that. You think this can be useful sometime? I mean, this makes some sense... but I'm unsure about that, because build all because `test` was changed seems be overkill. But sometimes can be useful too. I just don't was waiting for that.

> for push travis events fails, we need to add more verbose on the ./test to see whats happening

We can fix that easily skipping build for `push`... but If we can find something better, probably no. I'm insecure about that, but skipping is better than failing. We have on travis some ENV variables to control that behavior as we discussed on #136

**Comment by A-Hilaly** [comment]
> Hmm, I forgot about that. You think this can be useful sometime?

Depends on what useful means I believe we would use that too much (only if we want to generate new graphs. What about controllable build : travis ci build all solutions only if a environment variable exists and stats.py has been changed ?

> but I'm unsure about that
when `build_solutions()` in `stats.py` set _`problems=only` there is not check for files existing or not all what build_solutions get is a list of files that has been changed , added or removed it doesn't matter. I can fix this.

> We can fix that easily skipping build for push
I agree that is not a great idea. But we still didn't see whats the travis out put when we pull request with a new solution (instead of removing) ?

**Comment by A-Hilaly** [comment]
for #139 , to get lights on what should be done to complete the fixes ( Ill try to do it soon since it can affect any PR from new contributors ) :
- Recognizing added from removed files
- Build all only if stats.py has been changed ( for the moments its all the files at the main directory ) , and maybe an env var ?
- Rewrite clearer functions for `--build --files `

@ryukinix Am I missing something ? what do you think ?

**Comment by ryukinix** [comment]
> What about controllable build : travis ci build all solutions only if a environment variable exists and stats.py has been changed ?

You can hardcoded the filename getting by `sys.argv[0]`. For me, setting :travis env is pretty useless for that. 

> I agree that is not a great idea. But we still didn't see whats the travis out put when we pull request with a new solution (instead of removing) ?

Our problem is: seems that `push` doesn't have the `origin/master`, once we can find a workaround for that, we can fix that tests.

> @ryukinix Am I missing something ? what do you think ?

I'm ok with it, but I don't think that adding a env var can help. But we can implement that since would be easy disable this if we'll want later. Rewrite the functions for `--build` and `--files` is a good thing, for now it's seem to much mechanic/naive (checking `/` and so on), although is working in some way.

What I really want (as priority) is fix the `push` event bug.

**Comment by A-Hilaly** [comment]
> You can hardcode the filename getting by sys.argv[0]. For me, setting :travis env is pretty useless for that.

what I mean is sometimes you can just add comments or do modification on `stats.py `that wouldn't require rebuilding everything. something like `_IGNORE_FILES="stats.py stats.exs"`. what about a special string in commit/pr title like **[ignore stats.py] title**. anyways this can be done without all this vars or special title, for the moment ill try to fix the push event first. 

from travis docs: https://docs.travis-ci.com/user/environment-variables/
>[TRAVIS_BRANCH]:
for push builds, or builds not triggered by a pull request, this is the name of the branch.
for builds triggered by a pull request this is the name of the branch targeted by the pull request.
for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).

can we check for this var to know if its push or pr to ignore/allow tests ?

**Comment by ryukinix** [comment]
> what I mean is sometimes you can just add comments or do modification on stats.pythat wouldn't require rebuilding everything. something like _IGNORE_FILES="stats.py stats.exs". what about a special string in commit/pr title like [ignore stats.py] title. anyways this can be done without all this vars or special title, for the moment ill try to fix the push event first.

I understand that, but this will need to modify .travis.yml to add new env variables, no? I mean... this is not a practical thing to do. Changing a lot .travis.yml is not a good practice, since we'll have a lot of useless commits on our git history and I like to to write meaningful, atomic commits, I only squash when we don't have another option.

> can we check for this var to know if its push or pr to ignore/allow tests ?

Of course, let we see how this works.

**Comment by A-Hilaly** [comment]
> will need to modify .travis.yml to add new env variables, no?

Not really there is an little menu at each project settings ( at travis ). In general I used to use this to dd critical variables ( passwords, token keys etc )

<img width="1107" alt="travisenv" src="https://user-images.githubusercontent.com/10897901/32825310-d00c8ad8-c9e4-11e7-9849-584d64d98cf1.png">

@ryukinix I will open a PR trying to solve travis-ci/push build

**Comment by A-Hilaly** [comment]
Should I open PR using `git checkout x && git push -u origin x ?` like you said in #139 ? or just open it via GitHub or GitHub app @ryukinix

**Comment by ryukinix** [comment]
For testing `push` events that would be what I would do, I think is 
more easy. You can easily check. Since you already are member of 
DestructHub, probably will have write permissions to push a new branch 
on this repo. If you prefer creating a branch on your own fork this is 
ok too.

Let's test that.
-- 
As lembranças não são só do passado. Podem ser de agora e até de 
amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação,
Universidade Federal do Ceará.

**Comment by ryukinix** [comment]
Since we get into #143 all this shit is finished.
