### ISSUE TITLE
Discussion: Push master events

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#144]
@lubien and I was thinking about testing all the solutions when the push event is on master (only on master). This will ensure that after a merge all the solutions is working as expected. This is not a big problem on delay because no one cares about push events on master, since only occurs after a PR is merged. 

Why do you think about it?

**Comment by A-Hilaly** [comment]
> since only occurs after a PR is merged. 

Running all builds after a PR is merged seems nice. OK for me
