### ISSUE TITLE
Fail builds when solutions are uncorrect or timeout

### ISSUE THREAD

**Issue by A-Hilaly** [DestructHub/ProjectEuler#150]
We can implement this in `stats.py` to make travis-ci build status clearer

**Comment by ryukinix** [comment]
This is partially implemented on [stats.exs](stats.exs): if some solution takes more than one minute to terminates, the build system will complains that the one-minute rule is broken.

Making this feature happens on stats.py is importante because we use `stats.exs` to test the master push events, in contrast of PR tests using stats.py

**Comment by A-Hilaly** [comment]
We can use something like `timeout-decorator` or just use `alarm` built in lib to control build time.

**Comment by A-Hilaly** [comment]
@ryukinix I tried to use `alarm` to limit run time per solution execution. Actually I have this weird error (after command finish):
`Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe`
What I might be missing about `spin_thread` ?
You can see my modifications  [here](https://github.com/A-Hilaly/ProjectEuler/tree/updates)

**Comment by ryukinix** [comment]
I need to test to debug it... but unfortunately I don't have time now :/

I'll be available after 15 of December, but maybe you'll fix that until that day.

I saw this type errors on a few type of environments:

+ Multithreading
+ Popen
+ Shell pipelines operations with Python

Maybe you should remove some of your modifications carefully, step by step, to find the exactly point where this Exception occurs and why.

**Comment by A-Hilaly** [comment]
All fine ! Thanks for lighting up ! I will try to figure this out ASAP and prepare clean updates 👍
