### ISSUE TITLE
Cache docker images to speed up more travis build

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#154]
Our bottle-neck for now on time-issues is that always on PR we need to download sometimes unnecessary a new docker image, even if no updates was found on dockerhub. On these days, our PR build takes about 2 minutes to finish. Probably we can reduce to 1 minute if we cache docker images.

Similar approach: https://stackoverflow.com/questions/35305492/cache-docker-images-on-travis-ci

**Comment by A-Hilaly** [comment]
@ryukinix Would be awesome !

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
