### ISSUE TITLE
Allows stats.py receive --files as directory to build

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#158]
`python stats.py --build --files Problem001/`

Should build all the solutions of the `Problem001`. For now this is misleading

* `python stats.py --build --files Problem001` doesn't build anything
* `python stats.py --build --files Problem001/` build all solutions (?).

**Comment by ryukinix** [comment]
This can be useful to generate graphical insights about time analysis of each solution for a set of problems.

**Comment by A-Hilaly** [comment]
> python stats.py --build --files Problem001 doesn't build anything
python stats.py --build --files Problem001/ build all solutions (?).

I think this is good feature to add. We just avoid the maximum LEGO-ing the code.
