### ISSUE TITLE
[travis] correct setup of swift enviroment at .travis.yml

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#16]
We need the correct setup of Swift environment to build and check the solutions.

**Comment by rafaelcn** [comment]
Tick those boxes when you finish @luizperes 

[] Swift
[] Objective-C

**Comment by ryukinix** [comment]
Holy fuck, we already have a old issue here. I didn't saw that. Please, move to the new issue #121 created for that (more descriptive).
