### ISSUE TITLE
stats.py it's broken after partial build integration: handle_files has bugs

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#161]
After the PR #160 we can check this following error at this [log](https://travis-ci.org/DestructHub/ProjectEuler/builds/360092946?utm_source=github_status&utm_medium=notification):

```
Traceback (most recent call last):
  File "stats.py", line 747, in <module>
    main()
  File "stats.py", line 743, in main
    handle_options(options)
  File "stats.py", line 677, in handle_options
    uncommited_solutions, uncommited_core_files = handle_files(options.files)
  File "stats.py", line 512, in handle_files
    solutions += [(f, lang, solution) for lang in os.listdir(os.getcwd() + '/' + f)
```

This bug is related to the function handle_files and this it's definition:

https://github.com/DestructHub/ProjectEuler/blob/e6754604db9768dae7fbec50ff8f8aa017287403/stats.py#L497-L516

**Comment by A-Hilaly** [comment]
I checked this this morning, apparently `handle_files` doesn't take care of the case `README.md` and `.hash`. 😱 
I will open a PR fixing this soon.

**Comment by ryukinix** [comment]
Thanks, @A-Hilaly. Closing this issue.
