### ISSUE TITLE
Fix stats.py: solutions for compiled languages when load files it fails 

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#179]
There is some attempt to do this at fix/file-load branch.

**Comment by rafaelcn** [comment]
WHAT ARE YA DOING

**Comment by ryukinix** [comment]
Trying fix problems when someone need to use the filesystem in solutions, like loading a particular .txt file and so on. 

This doesn't works for C or C++. The problem is the class `Build` at https://github.com/DestructHub/ProjectEuler/blob/master/stats.py#L112. I pass changed_directory=False in pass just as Hack because passing as True breaks everything. 

There is some of this on this branch as I said: https://github.com/DestructHub/ProjectEuler/tree/fix/file-load
