### ISSUE TITLE
[go-hell-stdin] Check repository's consistency and execution time measurement 

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#2]
# Proposal

- [x] 1.Check if all the solutions process doesn't read nothing from stdin and print only the answer.
- [x] 2. Create a script for run all solutions and get the time of each.
- [x] 3. After all, we would compare the time solutions and rank by language or developer. Graphic representation can be cool.

# Hints/Ideas

1. Create a script for each language for executing and check if appears some gap reading from stdin
2. Again, create one script for each language only for execute. 
3. Join all the scripts in [2] so we call them to rank all the stuff and make graphics of benchmark.

# Stdin go hell Check and only-answer printing

- [x] C
- [x] C++
- [X] Clojure
- [x] CommonLisp
- [x] Elixir
- [x] Go
- [x] Haskell
- [x] Lua
- [x] Objective-C
- [x] PHP
- [x] Python
- [x] Swift
- [x] Ruby

## Building/Executing support on stats.py

- [x] C
- [x] C++
- [x] Clojure
- [x] CommonLisp
- [x] Elixir
- [x] Go
- [x] Haskell
- [x] Lua
- [x] Objective-C
- [x] PHP
- [x] Python
- [ ] Swift
- [x] Ruby

**Comment by ryukinix** [comment]
# Stdin go hell Check

- [ ] C
- [ ] C++
- [ ] Clojure
- [ ] CommonLisp
- [ ] Elixir
- [ ] Go
- [ ] Haskell
- [ ] Lua
- [ ] Objective-C
- [ ] PHP
- [ ] Python
- [ ] Swift

**Comment by ryukinix** [comment]
@luizperes, since you write the Swift, Objective-C and PHP solutions, you can check if all them don't read from stdin and only print the correct answer? Thanks.

**Comment by luizperes** [comment]
I know that they are not doing that, because I was the one who wrote them, but yeah :D, I can create a script for that ;)

**Comment by ryukinix** [comment]
I just was need that your answer! Doesn't need write a script for that, I guess.

The `stats.py` build/execute system working fine for `Python` and `Go`, I will check later for other languages.

**Comment by luizperes** [comment]
I will check that anyways and see if I can help with the others ones too

**Comment by ryukinix** [comment]
@rafaelcn you can check the Lua's solution when you have time?

**Comment by ryukinix** [comment]
I'll will check the `Haskell` solutions for now.

**Comment by rafaelcn** [comment]
Is there any Lua solution over the repo? :open_mouth:

**Comment by ryukinix** [comment]
Yes, some solutions! You can check the solutions using the utility of `stats.py -s lua -p`. But have some dependencies a little boring for guys whose doesn't commonly use python environment (pandas && numpy). See the output:

```
[lerax@starfox ProjectEuler (master)]$ python stats.py -s Lua -p
Problem001/Lua/solution_1.lua
Problem002/Lua/solution_1.lua
Problem004/Lua/solution_1.lua
Problem005/Lua/solution_1.lua
Problem007/Lua/solution_1.lua
Problem013/Lua/solution_1.lua
Problem015/Lua/solution_1.lua
Problem016/Lua/solution_1.lua
Problem032/Lua/solution_1.lua
[lerax@starfox ProjectEuler (master)]$ 
```

**Comment by ryukinix** [comment]
I think all Lua's solutions were written by @G4BB3R, including Elixir too.

**Comment by ryukinix** [comment]
Now you have that table
```
[lerax@starfox ProjectEuler (master)]$ python stats.py --list --count
             Solutions
Python              61
Haskell             20
Elixir               9
Lua                  9
Swift                6
C                    5
Clojure              4
C++                  4
Go                   2
CommonLisp           2 
Objective-C          1
PHP                  1
```
About CommonLisp, I'm writing a solution for P045.

**Comment by ryukinix** [comment]
@tkovs, you can check if all the Haskell solutions print only the correct answer?

**Comment by tkovs** [comment]
@ryukinix, yeah

**Comment by ryukinix** [comment]
If I try `python stats.py -s haskell -b`, we got: 
```
       Problem Language        Time        Answer
0   Problem001  Haskell    2.338591        233168
1   Problem002  Haskell    0.193601       4613732
2   Problem004  Haskell    2.136195        906609
3   Problem005  Haskell   10.057893     232792560
4   Problem006  Haskell    0.179550      25164150
5   Problem007  Haskell    1.145031          7929
6   Problem009  Haskell    0.415062      31875000
7   Problem010  Haskell   57.452556  142913828922
8   Problem012  Haskell    0.178839        126253
9   Problem013  Haskell    0.596420  "5537376230"
10  Problem014  Haskell  130.642537  (837799,525)
12  Problem015  Haskell    0.182069  137846528820
13  Problem015  Haskell    0.189623  137846528820
14  Problem016  Haskell    0.170585          1366
15  Problem020  Haskell    0.166739           648
16  Problem032  Haskell    3.739970         45228
17  Problem048  Haskell    0.192586    9110846700
```
So probably the wrongs solutions about his is problem 013 and 014. We have problems with performance at solutions about  10 and 31 either, but this is an other problem to worry it later.

**Comment by ryukinix** [comment]
@luizperes UFA! Now we need only setup at .travis.yml the correct steps to install the swift enviroment and get the cmdline to run the solutions.

**Comment by luizperes** [comment]
:+1:  .. that is going to be a bit hard xD I will try to help you when I get some time.. :(

**Comment by ryukinix** [comment]
This was be done. Just add new compilers and build later.
