### ISSUE TITLE
[travis] Correct setup of .travis.yml for build status, languages environment 

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#3]
- [X] Python
- [x] Haskell
- [x] C
- [x] C++
- [x] Go
- [x] Elixir
- [x] Lua
- [x] Clojure
- [ ] Swift
- [x] PHP
- [ ] Objective-C
- [x] CommonLisp
- [x] Bash
- [x] Ruby

**Comment by ryukinix** [comment]
Issue related at #13

**Comment by ryukinix** [comment]
Issue related at #15 too

**Comment by ryukinix** [comment]
Objective-C returns weird compilation error at P001 solution: 
```
$ gcc -lobj -lm solution_1.m
solution_1.m:1:34: fatal error: Foundation/Foundation.h: No such file or directory
compilation terminated.
```

**Comment by luizperes** [comment]
It's missing the Foundation flag on the cmdline

**Comment by luizperes** [comment]
Try to change the command line to:

```
gcc -std=c99 solution_1.m -framework Foundation -lobjc 
```

It should work..

**Comment by ryukinix** [comment]
HMMM! I'll try this. Thanks @luizperes !

**Comment by ryukinix** [comment]
This actually don't works. Maybe I need install some libs on Linux?

**Comment by ryukinix** [comment]
After fix C, I'll close this issue. I'm dropping Swift & Objective-C support until someone setup this.

**Comment by ryukinix** [comment]
WHY THIS FUCKING TRAVIS DON'T ALLOW ME TO COMPILE CODE WRITTEN IN C. 
![LAIN-ANGRY](http://blog.brycecampbell.me/user/files/lain_angry.jpg)

**Comment by ryukinix** [comment]
Bash is not working now after #115. We need install `gawk` on docker image to work.

**Comment by ryukinix** [comment]
Bash was fixed on #117

**Comment by rafaelcn** [comment]
We have to assign those two languages support to @luizperes :v

**Comment by ryukinix** [comment]
Yes, I'll close this issue and create a separated issue about that only for him. He deserve this.

**Comment by ryukinix** [comment]
After #120 be merged I'll close this issue, as described earlier.

**Comment by rafaelcn** [comment]
No problem :-)

**Comment by ryukinix** [comment]
Was a hell job until here. This issue deserves to be closed. Almost two years opened... oh god.

**Comment by ryukinix** [comment]
This issue should be continued here: #121
