### ISSUE TITLE
Proposal - 10 Next Problems

### ISSUE THREAD

**Issue by luizperes** [DestructHub/ProjectEuler#5]
For the 10 Next Problems, can we actually create a  new .md file named "Status.md" in order to get to know who is doing what?

Yesterday we were doing the Problem038 at the same time and I only realized after I pull it down from the server ... In that way, we could attack more solutions at the same time... That would be something like:

Problem041 [In Progress, @luizperes]
Problem042 [Done, @someone]

and so on...

**Comment by ryukinix** [comment]
@luizperes Nice ideia, write a Status.md file and push for us! 
We can use that snippet:


- [ ] Problem0XX
  - [ ] Python, @user
- [ ] Problem0XY

So if other user wants propose a solution in other lang at same time he'll got it.

**Comment by luizperes** [comment]
I will do it :)

**Comment by luizperes** [comment]
done.
