### ISSUE TITLE
Enhancement to the P005 Elixir solution

### ISSUE THREAD

**Issue by tkovs** [DestructHub/ProjectEuler#53]
Change the [range](https://github.com/DestructHub/ProjectEuler/blob/135a1ecf2c22635565bdf568d8abf5bef4f7087a/Problem005/Elixir/solution_slow_1.exs#L3) to `20,40...infinity` using lazy evaluation, it is better. I don't know how to do a range with steps in Elixir, so I just opened this issue.

**Comment by leorog** [comment]
Yeah, we could use ```Stream.unfold``` to generate our range. I will try something... BTW nice insight!

**Comment by leorog** [comment]
something like ```Stream.unfold(init_value, fn (x) -> {x, x + increase_rate} end)``` and then ```Enum.map_reduce``` it

**Comment by lubien** [comment]
`Stream.iterate(init_value, &(&1 + 1))` and `Stream.drop_while(not_divisible_by_all) |> Enum.take(1)`

**Comment by ryukinix** [comment]
Since we have alternative solutions in Elixir for this problem, I'll close this.
