### ISSUE TITLE
[stats] ShaSum hash solutions for each problem at ProblemXYZ/.hash

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#6]
We need generate the hash acceptable answer for each problem done and save on Problem folder.
- [x] Problem001
- [x] Problem002
- [x] Problem003
- [x] Problem004
- [x] Problem005
- [x] Problem006
- [x] Problem007
- [x] Problem008
- [x] Problem009
- [x] Problem010
- [x] Problem011
- [x] Problem012
- [x] Problem013
- [x] Problem014
- [x] Problem015
- [x] Problem016
- [x] Problem017
- [x] Problem018
- [x] Problem019
- [x] Problem020
- [x] Problem021
- [x] Problem022
- [x] Problem023
- [x] Problem024
- [x] Problem025
- [x] Problem026
- [x] Problem027
- [x] Problem028
- [x] Problem029
- [x] Problem030
- [x] Problem031
- [x] Problem032
- [x] Problem033
- [x] Problem034
- [x] Problem035
- [x] Problem036
- [x] Problem037
- [x] Problem038
- [x] Problem039
- [x] Problem040
- [x] Problem041
- [x] Problem042
- [x] Problem043
- [x] Problem044
- [x] Problem045
- [x] Problem046
- [x] Problem047
- [x] Problem048
- [x] Problem049
- [x] Problem050
- [x] Problem056
- [x] Problem062
- [x] Problem067
- [ ] ~Problem072 (unique solution deleted -- written in Python)~
- [x] Problem081
- [x] Problem092
- [x] Problem097
- [x] Problem099
- [x] Problem145
- [x] Problem500

**Comment by ryukinix** [comment]
Maybe is better only `.hash` instead `.solution_hash`

**Comment by ryukinix** [comment]
We are writing a bash script to handle this, see here: [add](https://codeshare.io/add-solution)

**Comment by lubien** [comment]
Lgtm

**Comment by lubien** [comment]
Added few hashes. See #47

**Comment by lubien** [comment]
Added 12. See: #60

**Comment by ryukinix** [comment]
Added more hashes on #65

**Comment by ryukinix** [comment]
Please, someone of @luizperes @tkovs or @lubien, even @leorog, can add the another hashes using the [add](add) script?

**Comment by ryukinix** [comment]
After merged the #98 this is finished.

**Comment by ryukinix** [comment]
FINALLY FINISHED.
