### ISSUE TITLE
C crazy float operation at Problem045, answer wrong, solution_1.c

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#7]
I don't know exactly what is wrong, but we have other 3 examples whose the answers are right: Go, Python and Swift.

**Comment by luizperes** [comment]
@ryukinix ...The return type of your function should be double, not float...that number is f*** big :D Vide https://github.com/DestructHub/ProjectEuler/commit/2e3a25a7fb3e282d240060de29c570ab4a2c2d10

**Comment by luizperes** [comment]
Fixed at the commit https://github.com/DestructHub/ProjectEuler/commit/6a2ca47a7ed9cd3d2355068e27f8e1ff3b5b51f5 ... I took most of libraries out for performance... :D
