### ISSUE TITLE
[P048] Overflows operation of type A^B. Langs: C, C++ and Go affected

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#8]
![captura de tela_2016-08-31_22-42-01](https://cloud.githubusercontent.com/assets/7642878/18152434/29cd98e2-6fcc-11e6-8f3b-4e8b6f86640c.png)

Overflow is the problem, very large number for large operation, need refactor `(A^B) mod C` operation.

**Comment by rafaelcn** [comment]
Could you please add a description on how to reproduce the bug? I'd be glad, and also would help hahaha. :boom: 

`-- on the wired --`

**Comment by ryukinix** [comment]
Just execute the solution. The problem is the overflow. Simple.

**Comment by rafaelcn** [comment]
On what problems should I execute the solution? This might be a "type error", where the programmer is using the wrong type for the task.

**Comment by ryukinix** [comment]
But this is not the question. The question is a better way to do the math operation `(A^B) mod C`.

**Comment by ryukinix** [comment]
What type we can use in C, at example, to do `1000^1000`? Is a number with 1003 zeros. 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.

Like this. What I can do?
